#!/sbin/busybox sh

#restore saved profile
if ls /data/backup.profile &> /dev/null; then
cp /data/backup.profile /data/.siyah/default.profile
echo "Restore completed"
else
echo "No backup to be restored!!!"
fi
