#!/sbin/busybox sh

link_lib() {
    local SRC_LIB=$1
    local DST_LIB=$2

    [ -f $SRC_LIB ] && chmod 644 $SRC_LIB
    rm -f $DST_LIB
    ln -s $SRC_LIB $DST_LIB
}

if [ "$2" ]; then
    skia=$2

    DEF_SKIA=/system/lib/libskia.so
    G2D_SKIA=/system/lib/libskia-fimg2d3x.so
    LIB_SKIA=/system/lib/libskia-default.so
    SAM_SKIA=/system/lib/libskia-samsung.so

    case "${skia}" in
	default)
	    SKIA=$DEF_SKIA
	    [ -f /data/config.txt ] && sed -i -e "s/^SKIA_TYPE=.*/SKIA_TYPE=0/g" /data/config.txt
	    ;;
	fimg2d3x)
	    SKIA=$G2D_SKIA
	    [ -f /data/config.txt ] && sed -i -e "s/^SKIA_TYPE=.*/SKIA_TYPE=1/g" /data/config.txt
	    ;;
	samsung)
	    SKIA=$SAM_SKIA
	    [ -f /data/config.txt ] && sed -i -e "s/^SKIA_TYPE=.*/SKIA_TYPE=2/g" /data/config.txt
	    ;;
    esac
    [ ! -f "$SKIA" ] && SKIA=$DEF_SKIA

    if [ -f $G2D_SKIA ] && [ -f $DEF_SKIA ]; then
	LINK_SKIA=$(readlink -f $LIB_SKIA);
	if [ "$LINK_SKIA" != "$SKIA" ]; then
	    if [ -f $SKIA ]; then
		mount -o remount,rw /system
		link_lib $SKIA $LIB_SKIA
		mount -o remount,ro /system
		[ "$LINK_SKIA" != "$LIB_SKIA" ] && REBOOT_SYSTEM=1
	    fi
	fi
    fi
fi

echo ${skia}
