#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  wifi_pm=$2
fi

mount o remount,rw /

case "${wifi_pm}" in
  off)
    echo "0" > /sys/module/dhd/parameters/wifi_pm
    ;;
  on)
    echo "1" > /sys/module/dhd/parameters/wifi_pm
    ;;
esac;

mount o remount,ro /

echo $wifi_pm
