#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  wifi_pm=$2
fi

mount -o remount,rw /

case "${wifi_pm}" in
  0)
    echo "0" > /sys/module/dhd/parameters/wifi_pm
    ;;
  1)
    echo "1" > /sys/module/dhd/parameters/wifi_pm
    ;;
esac;

mount -o remount,ro /

echo $wifi_pm
